### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by sh**
- [x] bump bluebird to 3.3.1
- [x] replace qs with query-string as qs will EOL soon
- [x] bump hinoki
- [x] bump react 
- [x] bump react-kup
- [x] bump passage

### CODE REVIEW

**Comment by sh** [comment]
bump react-kup and the tests will pass :octocat:

**Comment by snd** [comment]
https://github.com/snd/react-kup has a new version : )

**Comment by snd** [comment]
thanks !

what's the reasoning behind changing `REDIS_SESSION_STORE_PREFIX` to `REDIS_PREFIX` and the related changes ?

**Comment by sh** [comment]
redis changelog 2.4.0
`
Added prefix option to auto key prefix any command with the provided prefix
`

connect-redis changelog 3.0.2
`
Do not pass prefix option to redis client
`

**Comment by snd** [comment]
tests seem to hang for me locally.

i'll publish a new version as soon as i figure out the problem.

**Comment by snd** [comment]
see #9

**Pull request merged**
